spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/reservation
    username: postgres
    password: 20040725
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
        ddl-auto: update
    database: postgresql
    show-sql: true
server:
  port: 8081